build:
	gcc -Wextra -Werror -Wall vas_cat.c -o vas_cat
s21_cat:
	gcc -Wextra -Werror -Wall vas_cat.c -o vas_cat
all:
	gcc -Wextra -Werror -Wall vas_cat.c -o vas_cat
debug:
	gcc -Wextra -Werror -Wall vas_cat.c -o vas_cat -g
test: build
	bash diff_cat.sh